- arguments: [-XCPP]

- functions:
  - {name: unsafeCoerce, within: []} # banned

- ignore:
    name: Use const

- ignore:
    name: Avoid lambda
    within:
    - Data.Profunctor.Choice
    - Data.Profunctor.Traversing

- ignore:
    name: Use fmap
    within:
    - Data.Profunctor.Composition
    - Data.Profunctor.Strong
    - Data.Profunctor.Unsafe

- ignore:
    name: Avoid lambda
    within: Data.Profunctor.Strong

- ignore:
    name: Redundant lambda

- ignore:
    name: Collapse lambdas
    within: Data.Profunctor.Unsafe

- ignore:
    name: Eta reduce
    within:
    - Data.Profunctor.Mapping
    - Data.Profunctor.Choice
    - Data.Profunctor.Strong

- ignore:
    name: "Use tuple-section"

- ignore:
    name: "Avoid lambda using `infix`"

- fixity: "infixr 9 #."
- fixity: "infixl 8 .#"
- fixity: "infixr 0 :->"
